---
- name: expose grafana
  firewalld:
    port: "{{ grafana_http_port }}"
    permanent: true
    immediate: true
    state: enabled

- name: restart firewall
  service:
    name: firewalld
    state: restarted
...
