---
# Task file for Apache2 installation on RedHat
#-----------------------Instalación Apache2 RedHat-----------------------
- name: Apache2 installation
  yum:
    name: apache2
    state: latest

# Start apache service
- name: Start apache service
  service:
    name: apache2
    state: started

# Open ports in the firewall
- name: Open ports in firewall
  firewalld:
    service: https
    permanent: true
    state: enabled

# Open HTTP port (80)
- name: Open port 80 in firewall
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled

# Open HTTPS port (22)
- name: Open port 22 in firewall
  firewalld:
    port: 22/tcp
    permanent: true
    state: enabled

# Restart firewall and apply changes
- name: Restart firewall and apply changes
  service:
    name: firewalld
    state: reloaded

# Restart nginx
- name: Restart nginx
  service:
    name: nginx
    state: restarted
...
