---
- name: Install ufw
  apt:
    name: ufw
    state: latest

- name: expose grafana
  ufw:
    port: "{{ grafana_http_port }}"
    state: enabled

- name: Restart firewall
  service:
    name: ufw
    state: restarted
...
