---
- name: MariaDB Installation
  hosts: 192.168.10.44
  become: yes
  become_method: sudo
  roles:
    - mariadb

- name: Wordpress Installation
  hosts: 192.168.10.43
  become: yes
  become_method: sudo
  roles:
    - roles
...
